/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serverchat.application;

import serverchat.application. ServerChatApplication;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;       


/**
 *
 * @author Gábor
 */
public class loginserver extends javax.swing.JFrame {

    /**
     * Creates new form login2
     */
    public loginserver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jButtonbelepes = new javax.swing.JButton();
        jButtonreset = new javax.swing.JButton();
        jButtonexit = new javax.swing.JButton();
        jtxtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(1350, 1000));
        setMinimumSize(new java.awt.Dimension(773, 410));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Jelszó");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 20, 60, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Felhasználónév");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 20, 110, 20);

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword);
        jPassword.setBounds(580, 20, 130, 22);

        jButtonbelepes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonbelepes.setForeground(new java.awt.Color(51, 51, 51));
        jButtonbelepes.setText("Belépés");
        jButtonbelepes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonbelepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbelepesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonbelepes);
        jButtonbelepes.setBounds(10, 377, 70, 20);

        jButtonreset.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonreset.setForeground(new java.awt.Color(51, 51, 51));
        jButtonreset.setText("Reset");
        jButtonreset.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonresetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonreset);
        jButtonreset.setBounds(110, 377, 69, 20);

        jButtonexit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonexit.setForeground(new java.awt.Color(102, 102, 102));
        jButtonexit.setText("Bezárás");
        jButtonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonexit);
        jButtonexit.setBounds(620, 370, 70, 31);
        getContentPane().add(jtxtUsername);
        jtxtUsername.setBounds(370, 20, 130, 24);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gábor\\Desktop\\hooli-logo-white.png")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 80, 600, 250);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gábor\\Desktop\\3d-colorful-spiral-1057.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 740, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jButtonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonexitActionPerformed

    private void jButtonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonresetActionPerformed
        jtxtUsername.setText(null);
        jPassword.setText(null);
    }//GEN-LAST:event_jButtonresetActionPerformed

    private void jButtonbelepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbelepesActionPerformed
        String password = jPassword.getText();
        String username = jtxtUsername.getText ();
        
        if (password.equals("alma") && (username.equalsIgnoreCase("toussel")))
        {
            jtxtUsername.setText(null);
            jPassword.setText(null);
            systemExit();
            chat_server Info = new chat_server();
            Info.setVisible(true);
        }
        else
        {
           JOptionPane.showMessageDialog(null,"Invalid Login Details","Login Error",JOptionPane.ERROR_MESSAGE);
           jPassword.setText(null);
           jtxtUsername.setText(null);
            
        }   
            
    }//GEN-LAST:event_jButtonbelepesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginserver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonbelepes;
    private javax.swing.JButton jButtonexit;
    private javax.swing.JButton jButtonreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables
private void systemExit()
{
     WindowEvent winCloseing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
}
        
        
}

